name: kazoo-configs-core
base_branch: origin/master
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-configs-core
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: Kazoo core configuration
    description: |
      The Erlang Kazoo core and applications requires
      an initial configuration (config.ini) as well as
      some Erlang specific configuration. If you need
      help you can contact us via the dev mailing list
      or on IRC at #2600hz on FreeNode.

    dist: .el7.centos
    requires:
      centos7:
         sudo: {}
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r core %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/core

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/rsyslog.d
      rm -rf system/rsyslog.d/1-default-config-override.conf
      rm -rf system/rsyslog.d/5-rate-limits.conf
      cp -r  system/rsyslog.d/*.conf %{buildroot}/etc/rsyslog.d

      mkdir -p %{buildroot}/etc/logrotate.d
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        - mode: noreplace
          path: /etc/kazoo/core
        - mode: noreplace
          path: /etc/rsyslog.d/*kazoo-core*
        - mode: noreplace
          path: /etc/logrotate.d/*kazoo-core*
        - mode: noreplace
          path: /etc/security/limits.d/*kazoo-core*
      path:
        - /usr/sbin/kazoo-applications
        - /usr/sbin/kazoo-ecallmgr
        - /usr/lib/systemd/system/kazoo-applications.service
        - /usr/lib/systemd/system/kazoo-ecallmgr.service
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-applications
    package: kazoo-configs-core
    type: required
    branch: 'master'
